/**
 * 中国省份拼音 → 中文 映射表
 * 用于匹配 ECharts 地图中的省份名称
 */
export const provincePinyinToCN: Record<string, string> = {
  'anhui': '安徽',
  'aomen': '澳门',
  'beijing': '北京',
  'chongqing': '重庆',
  'fujian': '福建',
  'gansu': '甘肃',
  'guangdong': '广东',
  'guangxi': '广西',
  'guizhou': '贵州',
  'hainan': '海南',
  'hebei': '河北',
  'heilongjiang': '黑龙江',
  'henan': '河南',
  'hongkong': '香港',
  'hubei': '湖北',
  'hunan': '湖南',
  'jiangsu': '江苏',
  'jiangxi': '江西',
  'jilin': '吉林',
  'liaoning': '辽宁',
  'neimenggu': '内蒙古',
  'ningxia': '宁夏',
  'qinghai': '青海',
  'shandong': '山东',
  'shanghai': '上海',
  'shanxi': '山西',
  'shaanxi': '陕西',
  'sichuan': '四川',
  'taiwan': '台湾',
  'tianjin': '天津',
  'xinjiang': '新疆',
  'xizang': '西藏',
  'yunnan': '云南',
  'zhejiang': '浙江',
};

/**
 * 中国中文省份名 → 拼音 映射表
 */
export const provinceCNToPinyin: Record<string, string> = {
  '安徽': 'anhui',
  '澳门': 'aomen',
  '北京': 'beijing',
  '重庆': 'chongqing',
  '福建': 'fujian',
  '甘肃': 'gansu',
  '广东': 'guangdong',
  '广西': 'guangxi',
  '贵州': 'guizhou',
  '海南': 'hainan',
  '河北': 'hebei',
  '黑龙江': 'heilongjiang',
  '河南': 'henan',
  '香港': 'hongkong',
  '湖北': 'hubei',
  '湖南': 'hunan',
  '江苏': 'jiangsu',
  '江西': 'jiangxi',
  '吉林': 'jilin',
  '辽宁': 'liaoning',
  '内蒙古': 'neimenggu',
  '宁夏': 'ningxia',
  '青海': 'qinghai',
  '山东': 'shandong',
  '上海': 'shanghai',
  '山西': 'shanxi',
  '陕西': 'shaanxi',
  '四川': 'sichuan',
  '台湾': 'taiwan',
  '天津': 'tianjin',
  '新疆': 'xinjiang',
  '西藏': 'xizang',
  '云南': 'yunnan',
  '浙江': 'zhejiang',
};
